### ISSUE TITLE
Can I check if for a specific value?

### ISSUE THREAD

**Issue by Muzical84** [wycats/handlebars-site#102]
I'm using Handlebars to iterate through the output from a ColdFusion WSDL that pulls from a SQL Server 2012 database, and I can not change the format of data int he database because too many other things call it.  I'm looking up a bunch of addresses, and one is flagged primary, via "PRIMARY_FLAG: 'Y'"  Now, even if that's "N," if i understand the Handlebars documentation correctly, that'll still trigger an {{#if}} block in Handlebars.  I need to apply particular CSS, (via a span with a class,) if that flag is Y.  I also would rather whichever address has that flag display first, but I might be able to finagle that on my own?  I also need to know if "ADDRSTATUS_CODE" is "G" or not.  (I would've tracked all of this with bit fields in SQL Server, but most of this code was written when I was still in college...)

Is there ANY way I can do something along the lines of "{{#if PRIMARY_FLAG==='Y'}} ?

I ask this here and not on the main handlebars repo because, if this IS possible, it's a documentation question, not a problem with Handlebars itself.  (If this is NOT possible, then please say so so I can add it as a feature request on the main repo.)

**Comment by kpdecker** [comment]
You can use customer helpers or a library such as dashbars to implement this via subexpressions. The core library is avoiding adding specific helpers for this as the number of cases are numerous and we'd like to avoid bloat.
