### ISSUE TITLE
Transitional DTD - Handlebars W3C Invalidation 

### ISSUE THREAD

**Issue by acapellas4u** [wycats/handlebars-site#103]
Is there any way to validate these codeblocks so that they will pass w3c validation when using a dtd of transitional.

Line 916, column 64: there is no attribute "datetime"
…ss="reviewtimedateago"><time datetime="{{cooldate}}" class="tinyfont cursorhel…

and

Line 913, column 5: character data is not allowed here
    {{#each this}}
Line 927, column 5: character data is not allowed here
    {{/each}}

If you validate the home page of suttons.co.uk you will see the errors.

**Comment by kpdecker** [comment]
Precompiling your templates is going to be the route you want to go if you are concerned about strict validation.
