### ISSUE TITLE
What does "^" mean?

### ISSUE THREAD

**Issue by tudanmeng** [wycats/handlebars-site#107]
In http://handlebarsjs.com/expressions.html Whitespace Control section you can find code like this:
```javascript
{{#each nav ~}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```
However I cannot find any documents about what does "^" mean.
Does "^" mean "else" in an if block?
Thank you very much.

**Comment by kpdecker** [comment]
In this instance it is equivalent to else. That being said, I think the
docs might be out of date and that else is required now when used for
chained inverse blocks. Will investigate and update these docs or this bug
with the proper info. In the near term, {{else}} should work across all
versions.

**Comment by tudanmeng** [comment]
Thanks kpdecker.
