### ISSUE TITLE
Clarify that "segment-literal" notation applies to top level props

### ISSUE THREAD

**Issue by jmm** [wycats/handlebars-site#112]
In the Expression documentation can you please clarify that the "segment-literal" notation is also applicable to top level property names.

For example, given this context:

```js
{"some.thing": "something"}
```

You can include the following expression in a template:

```js
{{[some.thing]}}
```

The following also work. Is that an accident, or something that can be documented?:

```js
{{"some.thing"}}

{{'some.thing'}}
```

Thanks

**Comment by kpdecker** [comment]
This was introduced in 3.0 by 2a4819d75cba7513946af5cf28ee22881561814f but I must admit that I'd forgotten about it and had to look it up.

We should update the docs to note this new behavior.

@mmun, this was related to something htmlbars needed, right?

**Comment by mmun** [comment]
@kpdecker HTMLBars doesn't have the same semantics as Handlebars for literals. `{{'some.thing'}}` just generates the string `'some.thing'`.

**Comment by jmm** [comment]
Thanks @kpdecker! I didn't do a great job of explaining the issue here.

The example given for the "segment-literal notation" is `articles.[10].[#comments]`. The main thing I was referring to in this issue is clarifying that this syntax can also be used to reference top-level properties of the context, e.g.:

```
{{#each [some.thing]}}
<h1>{{[article.title]}}</h1>
```



My secondary question, which I see has been addressed in your commit, was whether these syntaxes (which also work) are supposed to work and can be documented as well:

```
{{"some.thing"}}
{{'some.thing'}}

Haven't tested, but assume that extends to the following as well
{{some."#comments"}}
{{some.'#comments'}}
```

**Comment by kpdecker** [comment]
Yes, it can be used for any variable reference location. Behavior does differ for strings in those locations though as they are treated as literals.

I.e.
`{{'foo'}}` will behave differently that `{{bar 'foo'}}`. The former will still look up the value named foo, but the later will provide pass the string `"foo"` to the helper.

Strings are not allowed in complex paths, so `{{some.'#comment'`}}` will not work right now:

```
Parse error on line 1:
Goodbye {{foo."foo bar"}} world!
--------------^
Expecting 'ID', got 'STRING'
```
