### ISSUE TITLE
`createFrame()` documentation is confusing

### ISSUE THREAD

**Issue by jmm** [wycats/handlebars-site#113]
In the [Block Helpers](http://handlebarsjs.com/block_helpers.html) documentation it says:

> Make sure you create a new data frame each time you invoke a block with data. Otherwise, downstream helpers might unexpectedly mutate upstream variables.

And illustrates calling `createFrame()` once per iteration of `context`. But in the [API Reference](http://handlebarsjs.com/reference.html) documentation on `createFrame()` it says:

> Generally only one frame needs to be created per helper execution, i.e. the `each` iterator only creates one frame which is reused for all child execution.

**Comment by kpdecker** [comment]
Sorry for the delay. I tried to clarify the example from the block helpers docs. Basically we consider it safe to reuse a frame within a given helper as this has much better performance, but you should not change a "parent" frame.

Please let me know if the docs are still confusing!

**Comment by jmm** [comment]
Thanks @kpdecker! That's definitely better as now there aren't 2 inconsistent versions. I meant to reply here sooner, but I realized I do still think it's confusing and was going to nail down what's confusing about it and put together some examples, but keep getting delayed. I'll ping you or open a new issue when I get the chance to do that.

**Comment by kpdecker** [comment]
Great, feedback on the docs is certainly appreciated as I feel like this is often one of my shortfalls on the project.
