### ISSUE TITLE
close current window

### ISSUE THREAD

**Issue by justQing00** [wycats/handlebars-site#116]
#####  This is my code :
```
  <html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script language="javascript">
      function closeWindow()
      {
        open(location, '_self').close();
        return false;
      }
    </script>
  </head>
  <body>
    <input type="button" name="Quit" id="Quit" value="Close This Window/Tab" onclick="return closeWindow();">
  </body>
  </html>
```

#####   "Scripts may close only the windows that were opened by it."

**Comment by kpdecker** [comment]
I'm not sure how this is related to handlebars. If you still believe this is an issue, please open an issue on @wycats/handlebars.js, following the process described in the [contributing doc](https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md#reporting-issues).
