### ISSUE TITLE
Comma between array items?

### ISSUE THREAD

**Issue by JeroenSF** [wycats/handlebars-site#119]
We are building an array and outputting this to a handlebars template. For some reason after compiling commas are added between the items in the array. These commas are not in the code and are not showing the debugger. Is this a bug in handlebars.js?

code snippets building array:
![2015-08-05 12_53_12-photos](https://cloud.githubusercontent.com/assets/13658711/9084167/f9c3fe88-3b70-11e5-815f-a7f65bc762c0.png)

Debugger output:
![2015-08-05 12_46_19-f12](https://cloud.githubusercontent.com/assets/13658711/9084144/ca76b634-3b70-11e5-9096-2d4d7f8fc1bc.png)

![2015-08-05 12_46_33-f12](https://cloud.githubusercontent.com/assets/13658711/9084169/0530c7ce-3b71-11e5-954c-80241cfbd4d9.png)

Browser DOM:
![2015-08-05 12_54_46-f12](https://cloud.githubusercontent.com/assets/13658711/9084191/5527d132-3b71-11e5-90d2-a54a28598118.png)

**Comment by kpdecker** [comment]
This repository is for the site and documentation. Could you please report this issue following https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md#reporting-issues. In particular we need a jsfiddle to help debug the issue.

**Comment by pdk2580** [comment]
Hi @JeroenSF ,
Do you have a solution for this? I think I am having the same issue.

**Comment by Jeroen00** [comment]
@pdk2580  no sorry, too long ago, can't remember if we worked this out or not...
