### ISSUE TITLE
Lookup helper in handlebars

### ISSUE THREAD

**Issue by chrisvdb** [wycats/handlebars-site#122]
A question rather than an issue... as I do not know where else to ask! I posted the question on [stackoverflow](http://stackoverflow.com/questions/32433381/lookup-helper-in-handlebars), but did not receive a response.

I have a 'countries' object which I pass as part of the Handlebars context:

    {
     'hk': {'name': 'Hong Kong', 'someotherprop': 'someothervalue'},
     'us': {'name': 'United States',  'someotherprop': 'yetanothervalue'},
     ...
    }

I want to use the lookup Handlebar helper to find from the countrycode 'hk' the name 'Hong Kong'.

I can get the following object

    {'name': 'Hong Kong', 'someotherprop': 'someothervalue'}

using the following Handlebars directive

    {{lookup ../countries countrycode}}

but how do I now extract the name property from this object?

**Comment by kpdecker** [comment]
You can chain lookup calls using the subexpression syntax

```
{{lookup (lookup ../countries countrycode) 'name'}}
```

**Comment by chrisvdb** [comment]
Works perfectly! Thanks a lot, Kevin.
