### ISSUE TITLE
Missing step - What to do with html variable after compilation

### ISSUE THREAD

**Issue by nateplusplus** [wycats/handlebars-site#124]
I'm fairly new to handlebars. I followed the getting started tutorial but I was getting a blank page. After doing a lot of Google searching I figured out that the html variable I created was actually an HTML string that needed to be directly inserted into the page. I think it's hard to understand what the compilation process is doing until you know that. I just think that step was never really made clear and maybe it should be added somewhere. Maybe include that step within the "execution" section?

**Comment by kpdecker** [comment]
Can you point me to the url in particular that you have concerns about?

**Comment by nateplusplus** [comment]
Oh sorry, yes I'm just talking about the "getting started" tutorial on the main page of http://handlebarsjs.com/ I looked through the "execution" page at http://handlebarsjs.com/execution.html and still did not see any reference on what to do with the html variable once everything is compiled.

**Comment by kpdecker** [comment]
I think this is outside the scope of handlebars itself. There are far too many ways for one to insert html into the document after it's created and many of are specific to the frameworks loaded on the page so we need to leave this to the user to determine.

**Comment by nateplusplus** [comment]
Ok, totally understood. I'm just saying, as a new user, I had no idea what "template(context)" was doing, so therefor I didn't know how to access the compiled HTML and insert it into my website. I just think it's missing some explanation, but I am a newbie so sorry if this is just too beginner level for your documentation.

**Comment by kpdecker** [comment]
I'll review true docs to see if they can better explain what is going on
without going into too many details on libraries.
