### ISSUE TITLE
Block helpers are not escaped by options.fn

### ISSUE THREAD

**Issue by Checkmarx2** [wycats/handlebars-site#126]

**Comment by Checkmarx2** [comment]
Taken from  handlebarsjs.com:
"Since the contents of a block helper are escaped when you call options.fn(context), Handlebars does not escape the results of a block helper. If it did, inner content would be double-escaped!".

Well, a simple example below demonstrates how the result of a block is not escape as described.
The result of running the HTML file is not escaped.
Since I failed to attach the files, I pasted the content below.

Regards,
Guy

=================
TestOptionsFN.html:
=================
<!DOCTYPE html>
<html>
<head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.3/handlebars.js"></script>
	<script src="TestOptionsFN.js"></script>
</head>


<script id="Test-3" type="text/x-handlebars-template">
	{{#Test data}}
		{{{field}}}
	{{/Test}}
</script> 
<div class="placeholder_3"></div>
</html>

=================
TestOptionsFN.js:
=================
$(function () {
Handlebars.registerHelper('Test' , function(theContext ,options) {
  return options.fn(theContext);
});

   var context={ "data": {  "field": "<h1>This text is supposed to be escaped</h1>" }
};
  
  var theTemplateScript = $("#Test-3").html(); 
  var theTemplate = Handlebars.compile(theTemplateScript); 
  var theCompiledHtml = theTemplate(context);
  $('.placeholder_3').html(theCompiledHtml); 
});

**Comment by kpdecker** [comment]
Please post this as a fiddle or other live example so we can debug it. The contributing.md document has a link to a temple fiddle.

**Comment by Checkmarx2** [comment]
Here is a fiddle:
http://jsfiddle.net/N2b5M/2112/

**Comment by kpdecker** [comment]
```
		{{{field}}}
```

means don't escape.
http://handlebarsjs.com/expressions.html#basic-blocks

**Comment by Checkmarx2** [comment]
As I said the documentation claims:
"Since the contents of a block helper are escaped when you call options.fn(context), <b>Handlebars does not escape the results of a block helper</b>. If it did, inner content would be double-escaped!".

Here is  a complementary fiddle that proves the fact that block helper result is escaped: http://jsfiddle.net/N2b5M/2113/

If {{field}} is actually escaping block helpers (as opposed to the documentation) and {{{field}}} overrides the escaping of options.fn, then it seems that only the mustaches determine whether escaping is performed.
