### ISSUE TITLE
extra commas

### ISSUE THREAD

**Issue by tonyspb** [wycats/handlebars-site#127]
http://handlebarsjs.com/builtin_helpers.html

```json```
{{#each array as |value, key|}}  <- no comma please
  {{#each child as |childValue, childKey|}}  <- no comma please
    {{key}} - {{childKey}}. {{childValue}}
  {{/each}}
{{/each}}

**Comment by dddomin3** [comment]
THIS, I JUST SPENT SO LONG FIGURING THIS OUT, D:

**Comment by adeubank** [comment]
YES, came here to bring this up.

**Comment by stones** [comment]
Made a PR to fix this: #141
