### ISSUE TITLE
Documentation missing for Path context scoping for Handlebars versions prior to 4

### ISSUE THREAD

**Issue by alysson-macys** [wycats/handlebars-site#134]
On Handlebars Paths section, it is mentioned that Handlebars 4, a new behavior of depthed paths were introduced (i.e. behavior of ../ inside #each helpers).

However, there is no mention of how was before. Seems that on Handlebars 3.03 it has similar behavior.

It would be nice to have documentation for these versions as well.

Thanks

**Comment by kpdecker** [comment]
We aren't actively supporting anything other than the latest version and all language in the docs should be relative to this version. Anything noting a change is just to assist users in upgrading to the new version. Please let me know if it's not clear on how the current version behaves.

**Comment by alysson-macys** [comment]
Ok cool. Thanks for the update.

Handlebars3 has differently behavior, and was able to completely understand
the difference after some tests.

On Handlebars3, every block helper adds one more level to the depthed path,
so this is one important thing to keep in mind while using relative
addressing to the parent content via '../'.
