### ISSUE TITLE
What scripts do I add to my html?

### ISSUE THREAD

**Issue by magick93** [wycats/handlebars-site#149]
This is a getting started question: I cannot find anywhere on your website that states what handlebar js files are to be explicitly added to the html file.

I have used bower, and it has download several files. Some are js files. Do I need to import each of these with a script tag, or just some? 

Thanks

**Comment by VincentVToscano** [comment]
You may download the file located at the address below or just put this in the head of your html page.

`<script rel="http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars.min-latest.js"></script>`
