### ISSUE TITLE
Typo error under Block parameters

### ISSUE THREAD

**Issue by imkikus** [wycats/handlebars-site#154]
"Parameters beyond this cound will never be referenced and can safely be omitted by the helper if desired"

There is a typo error in the ^ sentence. Replace the text "cound" with "count"

![image](https://cloud.githubusercontent.com/assets/10371390/15738568/9357366e-28c9-11e6-9f30-84470b01e108.png)

**Comment by nknapp** [comment]
Thanks, fixed it. (Yes, it's been a while, but I just stumbled across this one)
