### ISSUE TITLE
Error during template processing

### ISSUE THREAD

**Issue by maksspace** [wycats/handlebars-site#155]
I using Jade and Handlebars to developing web apps. 

``` jade
script#template-stat(type='text/x-handlebars-template').
     h1
     | Some header1
    canvas#stat
    script.
         // some javascript code
     h1
     | Some header2
```

header2 body is inserted at the beginning of each time . Jade works fine , and header2 inserted where needed. If all the scripts to write at the end of the template , this is no mistake

**Comment by nknapp** [comment]
I can't say much about Jade, but http://learnjade.com/. Could you show your problem in a jsfiddle, without Jade?
