### ISSUE TITLE
Need Navigation

### ISSUE THREAD

**Issue by yucheng-xu** [wycats/handlebars-site#160]
Can't navigate at all,  have to click home page to access Learn More.

**Comment by ffxsam** [comment]
Still an issue. Pretty tough to navigate the docs. :disappointed:

**Comment by LarryAzevedo** [comment]
I agree. The navigation has always frustrated me whenever I visit the site.  I would be more than happy to rework a version of the site to accommodate better/straight-forward navigation.  But only if people think it's worth me doing.  Please vote.

**Comment by nknapp** [comment]
New site it online
