### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by ajfarkas** [wycats/handlebars-site#163]
It appears that Handlebars requires jQuery (`$(body).append( template(context) )`), but the documentation doesn't make that explicit.

Another option is to reproduce that function as part of Handlebars, so it can be used on its own (maybe this is sacrilege, but not every project needs jQuery).

**Comment by emiloberg** [comment]
jQuery is not needed. As you can see from your line of code jQuery is only needed to update the DOM with the Handlebars generated markup. You can just as well do this with plain JS:

```
document.getElementById('someElementId').innerHTML = template(context)
```

**Comment by ajfarkas** [comment]
That's what I mean. But the documentation still shows jQuery for some
reason. Why add the extra step?

**Comment by CodeTheInternet** [comment]
https://github.com/wycats/handlebars-site/pull/165

**Comment by nknapp** [comment]
This should be resolved in the new docs.
