### ISSUE TITLE
Documentation issue for @partial-block

### ISSUE THREAD

**Issue by hjonin** [wycats/handlebars-site#164]
Hello,

I may have found a documentation issue for `@partial-block` usage. Indeed, if I am using it as explained, i.e. `{{> @partial-block }}` then I get the error `The partial @partial-block could not be found`. If I am using instead `{{ @partial-block }}` then it works well.

Thank you in advance!

**Comment by brightredchilli** [comment]
I can confirm that im also seeing this on: 4.0.6
The documentation in question is here: http://handlebarsjs.com/partials.html

**Comment by nknapp** [comment]
It works in 4.0.10: https://jsfiddle.net/9D88g/140/
