### ISSUE TITLE
Handlebars on both client and server side.

### ISSUE THREAD

**Issue by dheerajgoyal38** [wycats/handlebars-site#167]
I'm using handlebars.js template engine on client side and its working fine.I have made a helpers which contains my handlebars helpers.Now i want to use same handlebars templates on my server side(PHP). So i'm using handlebars.php(https://github.com/XaminProject/handlebars.php). Now i'm able to use my handlebars templates but i cant use my helpers.I need to write new helpers and they are quite complex to write helpers in handlebars.php. So is there any way to use the same helpers in handlebars.php. If not then is their any documentaion for adding helpers in handlebars.php.

we also have a server in grails. so it means i have to write helpers in grails too?

**Comment by nknapp** [comment]
I don't know if PHP and Grails have a JavaScript-engine (like Nashorn in Java), but I believe that the only way to use helpers on both client and server is NodeJS (or Nashorn in Java).
