### ISSUE TITLE
Invalid certificate for https://handlebarsjs.com/

### ISSUE THREAD

**Issue by nknapp** [wycats/handlebars-site#171]
@jonas-schievink reported in wycats/handlebars.js#1307

> I clicked a link to the HTTPS version of the Handlebars website, and Firefox refused to connect because > the certificate is only valid for a few GitHub subdomains. Just letting you know, since this does seem like > a scary error at first :)

**Comment by nknapp** [comment]
@wycats Configuring a property certificate for handlebarsjs.com is something you have to do.

I found these instructions: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by franklinyu** [comment]
Closed?
