### ISSUE TITLE
No support for Asynchronous requests to DOM objects

### ISSUE THREAD

**Issue by dwkrueger2** [wycats/handlebars-site#183]
I don't see any access to the DOM object after the rendering of the page.  This is important if the properties of the page need to change based on downloading data.

**Comment by nknapp** [comment]
The list at https://github.com/wycats/handlebars.js/blob/master/README.markdown#handlebars-in-the-wild contains some alternative projects that might help you (but I haven't looked at them myself). incremental-bars for example. Handlebars itself knows nothing about DOM, HTML or anything else (expect for escaping). Handlebars can be used for any other target format as well
