### ISSUE TITLE
arguments passed failed when using the helper functions inside embedded script of the template

### ISSUE THREAD

**Issue by stang1013** [wycats/handlebars-site#190]
Say I have a helper function:
```
HandleBars.registerHelp('format_time', (date_value)=>{
  if (date_value) return dataFormat(date_value, "HH:MM:ss");
  return "";
});
```
I have an hbs file(has embedded JavaScript) like this:
  
```
< table id ="dtable" >
< tbody >...< / tbody >
< /table >
 < script>
         function renderTime (data, type, row, meta) {
              //data passed is "Sat Feb 03 2018 12:12:12 GMT-0700 (Mountain Standard Time) "
              return `{{format_time data}}`;
         };
  < script>
```

In the renderTime function, we passed in actual value to data, say '2018-02-03 12:12:12', what format_date helper's date_value is always **undefined**, you can see the container.helpers's format_date's first argument is **undefine**d.

**Comment by nknapp** [comment]
If I understand correctly, you expect that the helper `format_time` is called by the `renderTime`-function.
But this is not the case. The helper is called, when you render the template. The "renderTime" function will contain the result-value of the helper as a string literal.

I expect that `data` is not part of the object that you pass to Handlebars' render-function. Then, indeed, `format_time` will be called with `undefined`. The render-result will be: 

```
< table id ="dtable" >
< tbody >...< / tbody >
< /table >
 < script>
         function renderTime (data, type, row, meta) {
              //data passed is "Sat Feb 03 2018 12:12:12 GMT-0700 (Mountain Standard Time) "
              return ``;
         };
  < script>
```
When you call the function, if will always return an empty string.

**Comment by stang1013** [comment]
Hi Nil,
Thanks for response, I just want to know, in javascript section, how to pass variable to handlebar helper function? e.g in test.hbs
 <script>
      function () {
       var dt = Date.now();
        return “{{format_time dt}}”;
      }
      
</script>

pass real value of dt into the helper instead of undefined? currently I’m using extra ajax call which is not elegant.

Best Regards
Steven

**Comment by nknapp** [comment]
I'm afraid that is not possible. If you render the template on the server, the helper function is not available in the browser. You have to make an ajax request.
