### ISSUE TITLE
Documentation not updated with version 4.0

### ISSUE THREAD

**Issue by isabeg** [wycats/handlebars-site#191]
It looks like the site has not been updated since Handlebars 3, this version being referenced as the newer version in the site.

Decorators are not documented and possibly newer features which I am not aware of.

I believe there is an error in the section Partial Context. I just cannot make it work the way it is explained. Is there some block helper missing?

I agree with previous comments that you can get lost on the site. One suggestion would be to create transfer the documentation in GitHub Doc. I believe it would be easier and faster to create and maintain than remaking a new web site. Would anybody have time to do that?

I believe that Handlebars would be more popular with a better documentation and examples because the learning path would be less steep and daunting. It looks that the Handlebars project is still going on and documentation should be updated with it.

**Comment by nknapp** [comment]
A new site is up now. Decorators will not be documented, because the current API is deprecated and should not be used. I would like to create new API some time. 
Inline partials (http://handlebarsjs.com/guide/partials.html#inline-partials) are created using decorators. They will remain.
