### ISSUE TITLE
Documentation for 'if' helper appears to be wrong.

### ISSUE THREAD

**Issue by mortenbekditlevsen** [wycats/handlebars-site#200]
From the following example on the 'built-in helpers' page:
```
<div class="entry">
  {{#if author}}
    <h1>{{firstName}} {{lastName}}</h1>
  {{/if}}
</div>
```
it appears that the context of the if-body is the author. But this is not directly stated in the documentation, and from my own tests it appears that the context does not change.

So IF the imagined example data is something like:
```
{ author: { firstName: "J. R. R.", lastName: "Tolkien" } }
```
Then the documentation appears to be wrong. In that case the template should be something like:
```
<div class="entry">
  {{#if author}}
    <h1>{{author.firstName}} {{author.lastName}}</h1>
  {{/if}}
</div>
```

But then again, if the imagined example data is:
```
{ author: true, firstName: "J. R. R.", lastName: "Tolkien" }
```
Then the template is correct (but confusing since the author-example is used elsewhere in the first fashion.

Perhaps it would be good to describe the similarities/differences between 'if' and 'with'.

**Comment by nknapp** [comment]
http://handlebarsjs.com/guide/builtin-helpers.html#if
