### ISSUE TITLE
Document wether or not indexes is a supported part of paths

### ISSUE THREAD

**Issue by mortenbekditlevsen** [wycats/handlebars-site#202]
In a template, I can refer to an index of an array as:
```
{{myArray.0.myField}}
```
I am not certain wether this is by design or a subtlety of javascript, because if it is by design I would assume that I could use the same syntax for a block (like `with`):
```
{{#with myArray.0}}
{{myField}}
{{/with}}
```
But the above does not appear to work - the closest I can get is:
```
{{#with myArray}}
{{0.myField}}
{{/with}}
```
This works, but it would be neat if the index could be passed directly to the `with` block.

From the documentation I haven't been able to figure out wether or not it is supposed to be possible to use this kind of direct indexing or not.

**Comment by milenvoutchev** [comment]
Well, documentation seems abandoned since a while.

**Comment by mortenbekditlevsen** [comment]
Right, I have an open PR for a documentation fix, but it seems to have stranded.

**Comment by nknapp** [comment]
I have the small problem that the site generator does not work anymore with current ruby versions.

We should have something new, but I haven't had the chance to set it up.

**Comment by nknapp** [comment]
Something new is up: http://handlebarsjs.com/guide/expressions.html#literal-segments

**Comment by nknapp** [comment]
https will take a while to work, since the site just moved
