### ISSUE TITLE
Different Layouts

### ISSUE THREAD

**Issue by arunlalkp** [wycats/handlebars-site#206]
How can I work with different layouts in hbs and I can't find any result in official documentation

**Comment by nknapp** [comment]
If you are using `express-hbs` or another layout-engine that uses handlebars, those typically have their own way of creating layouts.

If you are using plain Handlebars, you can use [partial-blocks](http://handlebarsjs.com/partials.html#partial-block) to achieve the same goal.

**Comment by arunlalkp** [comment]
Thank you :)
