### ISSUE TITLE
New handlebars-site

### ISSUE THREAD

**Issue by nknapp** [wycats/handlebars-site#207]
I have created a new draft site at https://handlebars-lang.github.com/docs
It is based on vuepress and all the content is markdown. 

I have moved some content over from the old site, but I think it needs a major content makeover.

Everyone who is interested is welcome to help out. Have a look at the issues.

**Comment by SacDin** [comment]
404
There isn't a GitHub Pages site here.

**Comment by nknapp** [comment]
Sorry, should be github.io

**Comment by nknapp** [comment]
The new site is online now.
