### ISSUE TITLE
Is this a typo in Basic Usage?

### ISSUE THREAD

**Issue by mydeveloper1** [wycats/handlebars-site#208]
On the page https://handlebarsjs.com/expressions.html, in the last paragraph in the Basic Usage section, I do not think that the word Handlebars and the dash "-" are needed at the beginning of the paragraph. It seems like that the paragraph reads as:

> Handlebars HTML-escapes values returned by a

Instead of:

> HTML escapes values

or at least:

> Handlebars HTML escapes values

With hope this helps,

-A.

**Comment by nknapp** [comment]
I am not a native speaker, but it seems to me that this emphasizes the meaning of "HTML-escaping" as opposed to "Handlebars HTML".

**Comment by mydeveloper1** [comment]
You sure are right, @nknapp ! Thanks!
