### ISSUE TITLE
Handlebars.js.app

### ISSUE THREAD

**Issue by julioMayorga** [wycats/handlebars-site#214]
I remember downloading an app unto my mac. Is that no longer available?

**Comment by nknapp** [comment]
I don't know if you mean that, but the preview/draft of the new site at https://handlebars-draft.knappi.org/ has PWA features and can probably be downloaded.

**Comment by julioMayorga** [comment]
that was exactly it. But, I remember being able to download it as an app. Is that no longer a possibility?

**Comment by nknapp** [comment]
I don't use a Mac, but when I go to that site, my browser offers me to install the site as an app. Doesn't it work for you?

**Comment by julioMayorga** [comment]
I don’t. It is weird.

**Comment by nknapp** [comment]
we'll soon move to other urls (handlebarsjs.com) anyway, maybe you can try again then.

But even without installing as app, it should function offline as long as you have a bookmark

**Comment by julioMayorga** [comment]
Ah got it. Okay, makes sense. I'll just use it offline. The app was pretty cool. I had to reformat my SSD, and I completely forgot to migrate that app. Thanks for the help though.

**Comment by nknapp** [comment]
I'm glad that the new documentation is helpful
