### ISSUE TITLE
npm.js install script has moved

### ISSUE THREAD

**Issue by edmundofuentes** [wycats/handlebars-site#64]
The second command in the Precompilation: Getting Started section is broken:

```
$ curl https://npmjs.org/install.sh | sh
```

It is throwing an error because the server is responding a 301 Moved Permanently (points to the same URL but with a 'www' added in the domain).  Therefore, the fix is to change the command to:

```
$ curl https://www.npmjs.org/install.sh | sh
```

Cheers,

**Comment by kpdecker** [comment]
Fixed by 5199d6a7a064561f255c559a29d90e42f51b218c
