### ISSUE TITLE
Handlebars precompile adds extension to template[name.ext] ... breaks stuff.

### ISSUE THREAD

**Issue by blaasvaer** [wycats/handlebars-site#65]
When precompiling I kept getting undefined when using precompiled templates. Found out that the precompiled version had the full template file name with extension. So the source file "template.html" would result in the compiled file having template["template.html"]. Removing the .html part made stuff work again.

Am I missing something here? Or do we have to manually remove file suffixes after compiling?

**Comment by kpdecker** [comment]
I'm guessing that you are using the precompiler CLI interface that is bundled in the library, if so then there is a argument that allows you to control what extensions are stripped.

BTW the @wycats/handlebars.js repository is a better place to file issues regarding handlebars' code and functionality. This repo is specific to the docs.
