### ISSUE TITLE
Documentation calls [] falsey; it isn't

### ISSUE THREAD

**Issue by tjcrowder** [wycats/handlebars-site#66]
On [this page](http://handlebarsjs.com/builtin_helpers.html) it says (right near the top):

> You can use the if helper to conditionally render a block. If its argument returns `false`, `undefined`, `null`, `""` or `[]` (a "falsy" value)...

The term "falsey" (or "falsy") has a well-defined meaning in JavaScript: It's anything that the spec's abtract [`ToBoolean` operation](http://www.ecma-international.org/ecma-262/5.1/#sec-9.2) will coerce to `false`, which is this list: `false`, `undefined`, `null`, `""`, `0`, and `NaN`. Importantly, `[]` is not falsey (nor is `{}`).

If Handlebars doesn't render the template if given `[]`, recommend removing the parenthetical *(a "falsey value")* from the page entirely.

**Comment by ricardograca** [comment]
@kpdecker Since you're updating the docs, can you look into this? If you accept @tjcrowder's suggestion I could send a pull-request with the change to save you the trouble :)

**Comment by kpdecker** [comment]
@ricardograca thanks for the offer, I was in there anyway, so I just dropped it.
