### ISSUE TITLE
paramter to template

### ISSUE THREAD

**Issue by oscaroxy** [wycats/handlebars-site#71]
How can I pass a parameter to template?

that is:

my obj: {name:"pippo", lastname:"pluto"}

my template: TAG_HTML {{name}} {{#if isParam}} {{lastname}} {{/if}} TAG_HTML

How can I pass the param isParam into template if it isn't into object?
isParam is a condition external from Model Object ... 
thanks

**Comment by jcrben** [comment]
I'm not really clear on what was being asked here. Seems like it could be worth closing this issue.

**Comment by kpdecker** [comment]
Closing this, but if you are still having issues, please file them against the wycats/handlebars.js project and include a repo case so we can better help.
