### ISSUE TITLE
Installation doc should be more accurate on Bower installation

### ISSUE THREAD

**Issue by tundo91** [wycats/handlebars-site#72]
Doc should better explain the Bower installation, as new in JS world i didn't get that i had to compile the project first and than import the js from ```dist/```.
The steps should be like:
- import ```"handlebars.js": "version_needed"``` in ```bower.json```
- run ```bower install```
- go to the ```bower_components``` folder
- run ```npm install``` (sudo may be needed!?)
- run ```grunt```
- inject manually in your ```index.html``` or whatever the reference to the desired handlebar file e.g.,
```	
<script src="/app/bower_components/handlebars.js/dist/handlebars.js"></script>
```

**Comment by jcrben** [comment]
@tundo91 could you provide the URL?

**Comment by kpdecker** [comment]
The handlebar repository is located here:
https://github.com/components/handlebars.js

**Comment by jcrben** [comment]
Do you think it's a good idea to provide detailed installation documentation on the site? There are very basic instructions at the [main repo](https://github.com/wycats/handlebars.js/). If not, should the issue be closed?

**Comment by tundo91** [comment]
Sorry guys I am no longer working on that project and I actually don't remember details.
What I remember is that the ```bower_install``` is not enough to have the handlebar.js available so needed to run ```npm install```...

**Comment by kpdecker** [comment]
I just realized the issue here, someone created a `handlebars.js` repository which points to the base git repo and runs into the issues noted above where you don't have the built libraries. Will find the appropriate place to document the best way to use this.
