### ISSUE TITLE
Document the need to set log level to be able to see any messages

### ISSUE THREAD

**Issue by ricardograca** [wycats/handlebars-site#91]
It's not obvious why nothing is being logged when using the `log` helper for the first time, when developing a new application. The documentation [here](http://handlebarsjs.com/builtin_helpers.html#log) makes it seem like it just works, when in fact it doesn't unless you explicitly set a low enough log level.

The only reference I could find to this issue (after a while trying to figure out if it was me doing something wrong) was the bug reports of people that also couldn't understand why nothing was being logged, and a very vague reference to log levels in [this page](http://handlebarsjs.com/reference.html). The problem with this reference is that it mentions the various log levels, and that it defaults to logging only error mode, but the `log` helper section doesn't mention that it is outputting messages with the `INFO` level. Also, if I was a new developer I probably wouldn't be very familiar with the standard error level hierarchy, so it's something that should also be better documented.

BTW, I only stumbled upon the reference to log levels by chance, since I would never have guessed that there was something in the Handlebars configuration that was preventing me from seeing log messages, or that I would need to read something unrelated to "Helpers" to get a helper working as intended.

**Comment by kpdecker** [comment]
We should update those docs to describe how it works in more detail... Although at some point we may want to consider reworking the logging as it is confusing and I'm not sure that we want to have a default level that doesn't log.

**Comment by ricardograca** [comment]
I agree that ideally logging should *just work* without having to configure anything. That's the usual expectation.

**Comment by kpdecker** [comment]
For the upcoming release, I've lowered the log level so it will log by default. I've also filed an issue to generally improve the API as a whole.
