### ISSUE TITLE
Explain that block helpers are identified by a # in front of their name

### ISSUE THREAD

**Issue by ricardograca** [wycats/handlebars-site#92]
This may be super obvious to you guys working on this for a long time but I just realized it after trying to figure why my custom helper was expecting a `CLOSE_RAW_BLOCK`.

To unexperienced users like myself there doesn't seem to be any logic behind the naming of helper tokens at first. Sometimes they are like this `{{#myHelper}}` and sometimes they are like this `{{myHelper}}` but it's not obvious that the first one is the way to call a block helper and that there must be a `{{/myHelper}}` to match it. This confusion is compounded by the fact that even the `{{else}}` statement doesn't need a `#` while the `{{#if}}` does.

**Comment by kpdecker** [comment]
Do you have any advice on where/how we could update the docs to make this clearer?

**Comment by ricardograca** [comment]
The first place I can think of is [here](http://handlebarsjs.com/#block-expressions). The text could be something like:

> ...a section of your template with a different context than the current. *They are identified by a `#` in
> front of their name, and require a matching closing expression that starts with a `/`*.

In [this page](http://handlebarsjs.com/block_helpers.html) in the top block is also a good place to include a similar description, since some people might skip the introduction on the Home page. Furthermore, when you're learning something new it helps if these basic concepts are repeated.

**Comment by kpdecker** [comment]
Thanks. I'm in the process of updating the docs for 3.0. I'll try to take this into account.
