### ISSUE TITLE
Graceful handling of compilation errors?

### ISSUE THREAD

**Issue by Shak-eah** [wycats/handlebars-site#96]
Hello, I'm trying to use Handlebars.compile for an html string with a javascript object that contains all data. Work beautifully when the properties match up - for e.g. {{userName}} wonderfully gets replaced with the value in the data object.

So, the following line works great for me: 

var template = Handlebars(htmlString, dataObject)
output = template(dataObject)

However, say the string passed in has an error - for e.g. instead of {{userName}}, the string has {{user Name}}.

On my server side, the error stops the execution of the entire application - I get a missing helper error, or 'has no method call' error and so on when I try to execute
template(dataObject).

Now, I have been handling this error using the JS's native try/catch approach, but is there anything built into Handlebars for graceful error handling that I can use?

[This is concerning to me because I'm executing compilation on the server side, so any sort of crash is... scary.]

**Comment by kpdecker** [comment]
That causes a helper invocation with the parameter `Name`. If your fields have spaces in them, then you need to use the id literal syntax: `{{[user Name]}}`.

**Comment by Shak-eah** [comment]
I understand the id literal syntax suggestion; thank you very much for the quick response. However, I still need to ask: is there a way to handle compilation errors aside from try/catch itself? Something akin to how PromiseArrays allow for a success and a failure function?

**Comment by kpdecker** [comment]
The API is designed around throwing on errors.
